services:
  library:
    platform: linux/amd64
    image: jhuguet/gaunal-library-ui:4.0.13
    container_name: gaunal-library
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  langchain-executor:
    platform: linux/amd64
    image: jhuguet/langchain-executor:1.0.0
    container_name: langchain-executor
    environment:
      - CELERY_BROKER_URL=pyamqp://guest@localhost:5672//
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0
      - LANGCHAIN_QUEUE=langchain_queue
      - CELERYD_NODES=langchain@%h
    network_mode: "host"
    ports:
      - "5001:5001"
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis
    container_name: redis-backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - shared_network
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - shared_network
    ports:
      - "5672:5672"
      - "15672:15672"

  chroma:
    image: chromadb/chroma:0.5.15
    container_name: chromadb
    networks:
      - shared_network
    ports:
      - "8000:8000"
    volumes:
      - /home/jjhuguet/tdg_jjho/TrabajoGradosClasificacion:/chroma/chroma

networks:
  shared_network:
    driver: bridge
