test_data = {
    "documents": [
        ["a person who designs buildings and oversees their construction.", "a professional who plans and supervises large structural projects"],
        ["an electronic device that processes data, performing calculations and tasks.", "a programmable machine that can execute a set of instructions."],
        ["an animal known for its loyalty and often referred to as 'man's best friend.'", "a domesticated mammal, often used as a pet or for security."],
        ["a large celestial body that orbits a star, usually spherical in shape.", "an object in space that revolves around a star, like the planets in our solar system."],
        ["a substance consumed to provide nutritional support for the body.", "material taken in by organisms to sustain life and provide energy."],
        ["a system that transports blood throughout the body, consisting of the heart and blood vessels.", "the heart pumps blood through a network of arteries, veins, and capillaries."],
        ["a written or spoken story, often involving fictional characters and events.", "a tale or account that entertains, informs, or conveys a moral lesson."],
        ["a legal binding agreement between two or more parties.", "a formal arrangement that outlines the terms and conditions agreed upon by the parties involved."],
        ["a practice that involves physical postures, breathing techniques, and meditation.", "an ancient discipline aimed at promoting physical, mental, and spiritual well-being."],
        ["a tool used to amplify or record sound, typically used in performances or recordings.", "an electronic device that converts sound into an electrical signal."],
        ["a vehicle designed for transporting goods or people over land.", "a motorized machine used for transportation, such as a car, truck, or bus."],
        ["an area where animals and plants live together in their natural environment.", "a specific place where a particular organism or community of organisms lives."],
        ["a period of 24 hours starting at midnight, used as a unit of time.", "the time it takes for Earth to complete one full rotation on its axis."],
        ["a piece of software used to browse and interact with content on the internet.", "a program that allows users to access and view websites."],
        ["a method of encoding data into a format that is unreadable without a decryption key.", "a technique used to secure data by converting it into a secret code."],
        ["a financial gain, usually the difference between the amount earned and the amount spent.", "the positive return on an investment or business activity after expenses."],
        ["an object in space made of ice, dust, and gas, with a bright tail when near the sun.", "a celestial body that appears as a bright ball with a trailing stream of particles."],
        ["a literary genre that focuses on imaginative and futuristic concepts, like space exploration and time travel.", "a category of fiction often dealing with advanced science and technology."],
        ["a large muscle located at the back of your lower leg, helping with movements like walking or running.", "the muscle in the calf that connects the heel to the back of the knee."],
        ["a form of precipitation consisting of ice crystals that fall from the sky in cold weather.", "frozen water vapor that forms delicate, white flakes and falls to the ground."],
        ["a neural network architecture commonly used in natural language processing tasks.", "a type of deep learning model designed to understand and generate text."], # LLM IA
        ["a technique that retrieves relevant information from external sources to provide more informed answers.", "a method used to enhance the accuracy of language models by incorporating real-time information."],
        ["the process of fine-tuning a pre-trained model using additional labeled data to improve performance on a specific task.", "an approach to customize a model's behavior to better align with the desired outputs."],
        ["a metric used to evaluate the performance of language models, measuring how well the model predictions match human judgment.", "a quantitative measure of a model's effectiveness in generating coherent and accurate text."],
        ["a specialized subset of artificial intelligence focused on understanding, interpreting, and generating human language.", "a field that enables computers to process and analyze large amounts of natural language data."],
        ["a large pre-trained model designed to generate human-like text by predicting the next word in a sequence.", "an artificial intelligence system that can perform various language-related tasks, such as summarization and translation."],
        ["the mechanism that selects the most probable words or sequences when generating text, affecting the creativity and diversity of model outputs.", "a parameter that influences how often the model chooses low-probability words."],
        ["a concept in which an AI model leverages external data or knowledge bases to answer questions more accurately.", "a strategy that combines real-time data retrieval with language model processing to provide updated and contextualized responses."],
        ["a framework that connects language models with various tools or data sources to perform complex tasks, like code generation or mathematical calculations.", "a system that integrates AI capabilities with external resources to solve specialized problems."],
        ["a type of embedding that represents words or phrases in a high-dimensional space, where semantically similar words are closer together.", "a way of converting words into numerical vectors that capture their meanings and relationships."],
        ["a mathematical model used to describe the relationship between the input and output of a control system.", "an equation that captures the dynamics of a system, often represented in terms of differential equations."], # AUTOMATED CONTROL
        ["a closed-loop system that automatically adjusts its input based on feedback to maintain the desired output.", "a system where the output is continuously monitored and used to adjust the control inputs."],
        ["a measure of how well a control system can handle disturbances or changes in system parameters without losing stability.", "a system's ability to maintain performance despite changes in its operating environment or uncertainties."],
        ["a control strategy that ensures the system remains stable and performs optimally by predicting future behaviors.", "a type of control that optimizes the system's output over a given time horizon using a model of the process."],
        ["the difference between a system's desired output and its actual output, often used to adjust the control input.", "an important concept in control theory that helps to refine and improve system performance."],
        ["a representation of a system's behavior in terms of its states, inputs, and outputs, often used in modern control theory.", "a mathematical framework that describes how the state of a system evolves over time based on its inputs."],
        ["a stability criterion used to determine if a system will remain stable by analyzing the location of poles in the complex plane.", "a method to assess the stability of linear systems using the properties of transfer functions."],
        ["an approach to control that ensures optimal performance by continuously adjusting based on the system's state.", "a control method that takes into account all possible future states to minimize a given cost function."],
        ["a measure of how quickly and accurately a control system responds to changes or disturbances.", "a system characteristic that reflects its ability to settle to the desired state efficiently."],
        ["a model used to represent systems that have multiple inputs and outputs, often used in complex control applications.", "a mathematical framework for analyzing and designing controllers for systems with multiple interacting variables."]
    ],
    "user_queries": [
        "What is an architect?",
        "What is a computer?",
        "What is a dog?",
        "What is a planet?",
        "What is food?",
        "What is the circulatory system?",
        "What is a narrative?",
        "What is a contract?",
        "What is yoga?",
        "What is a microphone?",
        "What is a vehicle?",
        "What is a habitat?",
        "What is a day?",
        "What is a web browser?",
        "What is encryption?",
        "What is profit?",
        "What is a comet?",
        "What is science fiction?",
        "What is the calf muscle?",
        "What is snow?",
        "What is a transformer model?", #LLM IA
        "What is Retrieval-Augmented Generation (RAG)?",
        "What is model fine-tuning?",
        "What is a language model evaluation metric?",
        "What is Natural Language Processing (NLP)?",
        "What is a large language model (LLM)?",
        "What is temperature in text generation?",
        "What is the concept of augmenting AI with external data?",
        "What is a LangChain framework?",
        "What is a word embedding?"
        "What is a system transfer function?", # AUTOMATED CONTROL
        "What is a feedback control system?",
        "What is robustness in control theory?",
        "What is Model Predictive Control (MPC)?",
        "What is error in a control system?",
        "What is a state-space representation?",
        "What is the Nyquist stability criterion?",
        "What is optimal control?",
        "What is system responsiveness?",
        "What is a multi-input multi-output (MIMO) model?"
    ],
    "expected_answers": [
        "An architect is a person who designs buildings and supervises their construction.",
        "A computer is an electronic device that processes data and performs calculations.",
        "A dog is a domesticated animal known for its loyalty and companionship.",
        "A planet is a large celestial body that orbits a star.",
        "Food is a substance consumed to provide energy and nutrients to the body.",
        "The circulatory system is the system that transports blood throughout the body.",
        "A narrative is a story or account of events and experiences.",
        "A contract is a legally binding agreement between two or more parties.",
        "Yoga is a practice that combines physical postures, breathing, and meditation for well-being.",
        "A microphone is a device used to amplify or record sound.",
        "A vehicle is a machine used for transporting people or goods over land.",
        "A habitat is an area where animals and plants live in their natural environment.",
        "A day is a period of 24 hours, the time it takes for Earth to rotate once on its axis.",
        "A web browser is a software program used to access and view websites on the internet.",
        "Encryption is a method of converting data into a secure code to prevent unauthorized access.",
        "Profit is the financial gain obtained when revenue exceeds expenses.",
        "A comet is an object in space made of ice and dust that develops a bright tail when near the sun.",
        "Science fiction is a genre of literature that explores imaginative concepts like advanced technology.",
        "The calf muscle is a large muscle in the lower leg that helps with movements like walking or running.",
        "Snow is frozen water vapor that forms ice crystals and falls from the sky in cold weather.",
        "A transformer model is a type of neural network architecture used in NLP tasks to understand and generate text.", #LLM IA
        "Retrieval-Augmented Generation (RAG) is a technique that enhances language models by retrieving relevant information from external sources.",
        "Model fine-tuning is the process of refining a pre-trained model using labeled data to improve performance on specific tasks.",
        "A language model evaluation metric measures how well a model's predictions align with human judgment.",
        "Natural Language Processing (NLP) is a field of AI that helps computers understand and generate human language.",
        "A large language model (LLM) is a pre-trained AI model that can generate human-like text and perform various language-related tasks.",
        "Temperature in text generation is a parameter that controls the randomness of the output by adjusting the probability distribution.",
        "Augmenting AI with external data involves using additional information to improve the accuracy and relevance of responses.",
        "The LangChain framework connects language models with tools and data sources to perform complex, specialized tasks.",
        "A word embedding is a numerical representation of words in a vector space, where similar words are closer together."
        "A system transfer function is a mathematical model that describes the input-output relationship of a control system.", # AUTOMATED CONTROL
        "A feedback control system is a closed-loop system that adjusts its input based on feedback to maintain the desired output.",
        "Robustness in control theory is the ability of a system to maintain stability and performance despite disturbances or uncertainties.",
        "Model Predictive Control (MPC) is a control strategy that uses a model to predict and optimize system performance over time.",
        "Error in a control system is the difference between the desired output and the actual output, used to adjust the control input.",
        "A state-space representation is a mathematical model describing a system in terms of states, inputs, and outputs.",
        "The Nyquist stability criterion is a method used to determine system stability by analyzing the poles in the complex plane.",
        "Optimal control is a control approach that continuously adjusts system inputs to achieve the best performance.",
        "System responsiveness refers to how quickly and accurately a control system reacts to changes or disturbances.",
        "A multi-input multi-output (MIMO) model is a representation of systems with multiple inputs and outputs, used in advanced control designs."
    
    ]
}
